# Generated by Django 3.0.6 on 2020-09-09 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0036_auto_20200909_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driving_license', models.ImageField(upload_to='documents')),
                ('aadhar_card', models.ImageField(upload_to='documents')),
                ('paasbook', models.ImageField(upload_to='documents')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Delivery_agent')),
            ],
            options={
                'db_table': 'agentdocs',
            },
        ),
    ]
