# Generated by Django 3.0.6 on 2020-09-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20200909_1940'),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent_docs',
            old_name='paasbook',
            new_name='passbook',
        ),
        migrations.AlterField(
            model_name='agent_docs',
            name='agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Delivery_agent'),
        ),
    ]
