# Generated by Django 3.0.6 on 2020-09-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20200911_1426'),
        ('agent', '0002_auto_20200909_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent_docs',
            name='aadhar_card',
            field=models.ImageField(default='None', upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='agent_docs',
            name='agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Delivery_agent'),
        ),
        migrations.AlterField(
            model_name='agent_docs',
            name='driving_license',
            field=models.ImageField(default='None', upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='agent_docs',
            name='passbook',
            field=models.ImageField(default='None', upload_to='documents'),
        ),
    ]
