# Generated by Django 3.0.6 on 2020-09-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_user',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_picture'),
        ),
        migrations.AlterField(
            model_name='reg_user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Buyer')], default='buyer', max_length=100),
        ),
    ]
