# Generated by Django 3.0.6 on 2020-09-03 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200903_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_name', models.CharField(max_length=100)),
                ('cuisine_photo', models.ImageField(upload_to='cuisine_photos')),
            ],
            options={
                'db_table': 'cuisine',
            },
        ),
        migrations.CreateModel(
            name='delivery_agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('passowrd', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='profile_picture')),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Buyer')], default='buyer', max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('docs', models.ImageField(upload_to='documents')),
            ],
            options={
                'db_table': 'delivery_agent',
            },
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('mobile_number', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='profile_picture')),
                ('status', models.CharField(max_length=100)),
                ('cuisine_name', models.CharField(max_length=100)),
                ('price_for_two', models.IntegerField()),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
        migrations.RemoveField(
            model_name='reg_user',
            name='user_id',
        ),
        migrations.CreateModel(
            name='ambience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='ambience_photos')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.restaurant')),
            ],
            options={
                'db_table': 'ambience',
            },
        ),
    ]
