# Generated by Django 3.0.8 on 2020-09-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200903_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
