# Generated by Django 3.0.6 on 2020-09-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200904_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambience',
            name='status',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
