# Generated by Django 3.0.6 on 2020-09-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('feedback_date_time', models.DateTimeField()),
                ('feedback_message', models.TextField()),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
